### ISSUE TITLE
Make parbot's status command handle empty teams

### ISSUE THREAD

**Issue by dvankley** [jusroberts/pingpong-web-server#32]

**Comment by dvankley** [comment]
[Wed May 11 2016 14:20:53 GMT-0400 (EDT)] DEBUG Message '!pong status' matched regex //^\s*[@]?(?:ParBot[:,]?|![:,]?)\s*(?:pong\s+status$)/i/
[Wed May 11 2016 14:20:53 GMT-0400 (EDT)] DEBUG Executing listener callback for Message '!pong status'
[Wed May 11 2016 14:20:54 GMT-0400 (EDT)] ERROR TypeError: Cannot read property 'team_a' of undefined
  at /opt/parbot/releases/ce2ab6d947ff66e8b3811104b4a055effa477783/scripts/pong.coffee:35:27, <js>:28:62
  at IncomingMessage.<anonymous> (/opt/parbot/shared/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:910:16
  at process._tickCallback (node.js:415:13)
